let str = 'Privet mir';
console.log(str);
let str1 = 'Privet ';
let str2 = 'mir!';
console.log(str1 + str2);
let name = 'Zhanat ';
console.log(name + 'privet!');
let ran = Math.random();
alert(ran ** 2);
let str3 = 'abcde';
console.log(str3[0]);
console.log(str3[2]);
console.log(str3[4]);
let num = '12345';
console.log(num[0] * num[1] * num[2] * num[3] * num[4]);
let hour = 17;
let minute = 10;
let sec = 59;
console.log(hour + ':' + minute + ':' + sec);
let a = 10;
alert(a ** 2);
var num1 = 47;
num1 += 7;
num1 -= 18;
num1 *= 10;
num1 /= 15;
alert(num1);
var num2 = 10;
num2++;
num2++;
num2--;
alert(num2);